#!/bin/bash

echo "Started azar_ddns script"

ipv6=$(ip -6 addr show dev enp6s0 | grep -m 1 -oP 'inet6 \K[0-9a-fA-F:]+/[0-9]+ scope global (?!temporary|deprecated)' | awk -F"/" '{print $1}')
dns_aaaa=$(dig aaaa rs.azar.lol +short)
echo "host ipv6 address is $ipv6"
echo "dns aaaa record is $dns_aaaa"

if [[ "$ipv6" == "$dns_aaaa" ]]; then
    echo "no ipv6 address change detected, exiting..."
    exit 0
fi



